[package]
name = "russh-sftp"
version = "1.2.1"
edition = "2021"
description = "SFTP subsystem supported server and client for Russh"
readme = "README.md"
repository = "https://github.com/AspectUnk/russh-sftp"
license = "Apache-2.0"
keywords = ["russh", "sftp", "ssh2", "server", "client"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", default-features = false, features = ["io-util", "rt"] }

num-derive = "0.3"
num-traits = "0.2"
num = "0.4"

async-trait = "0.1"
thiserror = "1.0"
bitflags = "2.2"
chrono = "0.4"
bytes = "1.4"
log = "0.4"

[dev-dependencies]
russh = "0.37"
russh-keys = "0.37"
env_logger = "0.10"
anyhow = "1.0"
